### ISSUE TITLE
Create wireframes for Upload internship student & company data feature

### ISSUE THREAD

**Issue by Balqiskinanti** [devops-assignment1-team1/ias#1]
**Requirements**
- [x] Create wireframe to upload .xlxs file (student & company) from local comp to db
- [x] Display corresponding message when success/fail.

**Pull Requests**
- no PR

**Comment by chuadongen** [comment]
https://www.figma.com/file/VZMJNHUMMnCRGrbK8OXuo9/Untitled?node-id=0%3A1&t=bM0eZfsB7Lq99ElN-1

**Comment by NPLeeWenKang** [comment]
LGTM
