### ISSUE TITLE
Create frontend main page

### ISSUE THREAD

**Issue by Balqiskinanti** [devops-assignment1-team1/ias#11]
**Requirements**

- [x] Upload file button + text
- [x] Match student button + text
- [x] Prepare emails button + text
- [x] Settings button + text

**Comment by Balqiskinanti** [comment]
**Current page**


![Image](https://user-images.githubusercontent.com/72959939/212675881-d02d8faa-37ef-496f-95a4-4a31af8d9151.png)


**Unit test results**


![Image](https://user-images.githubusercontent.com/72959939/212675922-373d528b-7616-43fc-87f4-187ace934bac.png)

**Comment by NPLeeWenKang** [comment]
LGTM
