### ISSUE TITLE
Create frontend settings page

### ISSUE THREAD

**Issue by chuadongen** [devops-assignment1-team1/ias#13]
Requirements:

- [x]  Upload email path
- [x] Upload resume path
- [x] Upload internship period
- [x] Unit test for email path render
- [x] Unit test for resume path render
- [x] Unit test for internship period render
- [x] Unit test for change state of save button
- [x] Unit test to load and get settings
- [x] Unit test to post settings

**Comment by Balqiskinanti** [comment]
**Unit test**

![Image](https://user-images.githubusercontent.com/72959939/213904311-f0957744-3f01-447b-9c69-3eb38fd90ebe.png)


**Page**

initial
![Image](https://user-images.githubusercontent.com/72959939/213904591-e19db47f-d799-40ab-a06b-28b1587e5011.png)

internship date picker
![Image](https://user-images.githubusercontent.com/72959939/213904602-ac077134-2fdd-47a6-a5a2-8c7b02f72df6.png)

directory modal (resume + email)
![Image](https://user-images.githubusercontent.com/72959939/213904614-624cd473-aaad-4f61-92e4-fbe18769bab9.png)

all 3 fields changed
![Image](https://user-images.githubusercontent.com/72959939/213904625-bb0eeca4-a962-41b9-842f-e769cbb261ce.png)

saved changes
![Image](https://user-images.githubusercontent.com/72959939/213904636-05ebdc2d-4632-4c30-b57c-c34cd4f9e9fd.png)

**Comment by Balqiskinanti** [comment]
Fixed title state 


![Image](https://user-images.githubusercontent.com/72959939/214352833-d8fe7bc0-e6c9-40c8-af09-f840934cd245.png)

**Comment by Balqiskinanti** [comment]
Added test when save changes disabled state is supposed to be unchanged when no changes are made

**Comment by NPLeeWenKang** [comment]
LGTM
