### ISSUE TITLE
Create Dev Frontend Push Pipeline

### ISSUE THREAD

**Issue by NPLeeWenKang** [devops-assignment1-team1/ias#14]
**Requirements**

- [x] On push /frontend folder.
- [x] Run Jest.
- [x] Display test results.
- [x] Upload test report artifect.

**Pull Request**
1. https://github.com/devops-assignment1-team1/ias/pull/15

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/212705650-48a8a38b-8140-41ea-827e-adf499b46fd9.png)

workflow runs on push that affects `/frontend` or when the workflow file gets updated.

**Comment by chuadongen** [comment]
LGTM
