### ISSUE TITLE
Create wireframes for Prepare Email feature

### ISSUE THREAD

**Issue by verrgod** [devops-assignment1-team1/ias#16]
**Requirements**
- [x] Table of students including ID, name, preferences and assigned company.
- [x] QOL features such as search filtering and multi-select.
- [x] Display corresponding message when success/fail of generating emails. 
- [x] Display alert to show students without resume upon email generation.

**Pull Requests**
- no PR

**Comment by chuadongen** [comment]
https://www.figma.com/file/VZMJNHUMMnCRGrbK8OXuo9/Untitled?node-id=0%3A1&t=bM0eZfsB7Lq99ElN-1

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/213150817-4688ff71-867f-4f11-bbc9-4e72c3addb8a.png)

Is fine but it would be better to show which feature is optional and which is not optional.

Required:

1. Display student x company with pending status
2. Prepare email button

Optional:

1. Searching
2. Pagination
3. download csv

**Comment by verrgod** [comment]
![image](https://user-images.githubusercontent.com/74231870/213418072-a619a787-504a-4ee8-bf3f-faae93b4c28c.png)
![image](https://user-images.githubusercontent.com/74231870/213418156-e3aa0ee2-83e1-4271-bd3a-5bfa67dabdda.png)

Indicated optional requirements for related Prepare Email pages.

**Comment by NPLeeWenKang** [comment]
LGTM
