### ISSUE TITLE
Create wireframes for Settings feature

### ISSUE THREAD

**Issue by verrgod** [devops-assignment1-team1/ias#17]
**Requirements**
- [x] Create wireframe to update directory for email and resumes.
- [x] Date picker to choose internship period.
- [x] Display corresponding message when success/fail of saving changes.

**Pull Requests**
- no PR

**Comment by chuadongen** [comment]
https://www.figma.com/file/VZMJNHUMMnCRGrbK8OXuo9/Untitled?node-id=0%3A1&t=bM0eZfsB7Lq99ElN-1

**Comment by NPLeeWenKang** [comment]
LGTM
