### ISSUE TITLE
Create Main PR Pipeline

### ISSUE THREAD

**Issue by DevOps-Team-1-2022** [devops-assignment1-team1/ias#18]
**Requirements**

- [x] Perform backend, frontend and SQL unit tests.
- [x] Display unit test results
- [x] Trigger sonarcloud scan
- [x] Trigger integration tests (leave out for now)
- [x] Send notifications to appropriate stakeholder.

**Pull Requests**

1. https://github.com/devops-assignment1-team1/ias/pull/19
2. https://github.com/devops-assignment1-team1/ias/pull/26

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/213126708-e90780ec-1637-4bb0-ad70-de8cecb514e9.png)

**Comment by chuadongen** [comment]
LGTM
