### ISSUE TITLE
Create wireframes for Match students feature

### ISSUE THREAD

**Issue by Balqiskinanti** [devops-assignment1-team1/ias#2]
**Requirements**
- [x] Table of students including student name, preferences , company dropdown and status dropdown.
- [x] Display some form of pagination.
- [x] QOL features such as search filtering and multi-select -> go to student details

**Comment by chuadongen** [comment]
https://www.figma.com/file/VZMJNHUMMnCRGrbK8OXuo9/Untitled?node-id=0%3A1&t=bM0eZfsB7Lq99ElN-1

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/213150311-bfebf9b3-74bd-47fd-9bd8-515077d7332d.png)

We do not include the 3 dots to "view profile" as our database only contains the student name and preference, status and student id. There are no more information that can be displayed.

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/213151535-fd960ac9-d4da-4015-acbd-858487754824.png)

We don't need this page because everything here can be seen on the "Match Student" UI. All the data here is duplicate.

**Comment by NPLeeWenKang** [comment]
LGTM
