### ISSUE TITLE
Prototype wireframe with basic flow of all features

### ISSUE THREAD

**Issue by verrgod** [devops-assignment1-team1/ias#20]
**Requirements**
- [x] Ensure pages flow without breaking.
- [x] Flows should provide basic demonstration of how feature works.
- [x] Display uccess/fail messages for different pages.

**Pull Requests**
- no PR

**Comment by chuadongen** [comment]
https://www.figma.com/file/VZMJNHUMMnCRGrbK8OXuo9/Untitled?node-id=0%3A1&t=bM0eZfsB7Lq99ElN-1

**Comment by NPLeeWenKang** [comment]
LGTM
