### ISSUE TITLE
Integrate sonarcloud for monitoring and metrics

### ISSUE THREAD

**Issue by DevOps-Team-1-2022** [devops-assignment1-team1/ias#21]
This ticket is for SonarCloud's main branch analysis.

**Requirements**

- [x] Trigger on Push
- [x] Trigger frontend and backend unit tests to get coverage results
- [x] Trigger sonarcloud scan

**Pull Request**

1. https://github.com/devops-assignment1-team1/ias/pull/27

**Comment by NPLeeWenKang** [comment]
https://sonarcloud.io/summary/overall?id=devops-assignment1-team1_ias

**Comment by chuadongen** [comment]
LGTM
