### ISSUE TITLE
Create backend for settings

### ISSUE THREAD

**Issue by chuadongen** [devops-assignment1-team1/ias#22]
**requirements**

- [x] Get settings
- [x] Post settings
- [x] Create directories
- [x] Unit test for get
- [x] Unit test for post
- [x] Unit test for create directories

**Comment by Balqiskinanti** [comment]
1. POST: /api/v1/settings

Body: 
{
    "email_dir":"MIA",
    "resume_dir":"yes iam",
    "internship_period":"yes"
}

2. GET: /api/v1/settings

**Comment by Balqiskinanti** [comment]
**Unit tests**

create directory test is inside post
![Image](https://user-images.githubusercontent.com/72959939/214102521-8d984182-1c55-41c3-9a60-908729b0f780.png)

**Comment by NPLeeWenKang** [comment]
LGTM
