### ISSUE TITLE
Create Dev Backend Push Pipeline

### ISSUE THREAD

**Issue by NPLeeWenKang** [devops-assignment1-team1/ias#24]
**Requirements**

- [x] Set up database using docker
- [x] Run Jest test
- [x] Display test result
- [x] Upload artifact

**Pull Requests**

1. https://github.com/devops-assignment1-team1/ias/pull/25
2. https://github.com/devops-assignment1-team1/ias/pull/26

**Comment by chuadongen** [comment]
LGTM

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/213418659-b0ed0359-0cd6-45b1-91f6-bd8da5ce3e7f.png)
