### ISSUE TITLE
Create database init script and initial data

### ISSUE THREAD

**Issue by NPLeeWenKang** [devops-assignment1-team1/ias#3]
**Requirements**

![Image](https://user-images.githubusercontent.com/73012553/212675005-70fb0eb6-0471-4b68-a488-f29f5992aec0.png)

- [x] Create tables
- [x] Insert initial data

**Pull Requests**

1. https://github.com/devops-assignment1-team1/ias/pull/6

**Comment by chuadongen** [comment]
Does the current database design accommodate the same student doing multiple internships/companies

**Comment by NPLeeWenKang** [comment]
It does not. Currently their relation is 1:1.

**Comment by chuadongen** [comment]
Ok, LGTM. KIV this issue
