### ISSUE TITLE
Create frontend upload data page

### ISSUE THREAD

**Issue by verrgod** [devops-assignment1-team1/ias#30]
Requirements:

- [x] Pull internship period to display in upload page
- [x] Upload student internship data
- [x] Upload company internship data
- [x] Unit test for internship period render
- [x] Unit test for student path render
- [x] Unit test for resume path render

**Comment by verrgod** [comment]
**Unit Test**


![Image](https://user-images.githubusercontent.com/74231870/215096309-1c247294-a2a7-4f00-8e3f-cec906d268f0.png)

**Page**


![Image](https://user-images.githubusercontent.com/74231870/215096481-51a45370-4672-492d-ba3f-4ef770dae523.png)

**Comment by chuadongen** [comment]
LGTM

**Comment by NPLeeWenKang** [comment]
LGTM
