### ISSUE TITLE
Create backend for upload data page

### ISSUE THREAD

**Issue by verrgod** [devops-assignment1-team1/ias#31]
Requirements:

- [x] POST students
- [x] POST companies
- [x] Test for POST /students/upload
- [x] Test for POST /companies/upload

**Comment by verrgod** [comment]
1. POST: /api/v1/companies/upload

2. POST: /api/v1/students/upload

**Comment by chuadongen** [comment]
LGTM

**Comment by DevOps-Team-1-2022** [comment]
LGTM (From Wen Kang)

**Comment by Balqiskinanti** [comment]
💯 **Frontend view (internship period got from settings):**
![Image](https://user-images.githubusercontent.com/72959939/215303383-cdfcfdeb-d8ee-47b2-8d1e-32e9da9ddb1c.png)

Uploaded:
- StudentData.XLSX
![Image](https://user-images.githubusercontent.com/72959939/215303444-beaed6e6-3446-423e-b58f-c7799457c993.png)



- CompanyData.XLSX
![Image](https://user-images.githubusercontent.com/72959939/215303406-c4be368d-8def-4970-b589-09bfd552aaed.png)




💯 **Updating Student Table**

![Image](https://user-images.githubusercontent.com/72959939/215302966-4589b19f-1e9f-4e4d-b8d3-840ade4fb558.png)

UPLOADED StudentDataXLSX

![Image](https://user-images.githubusercontent.com/72959939/215303265-0aa483a5-6c70-42fc-b041-79c4f513190a.png)


💯 **Updating Company Table**

![Image](https://user-images.githubusercontent.com/72959939/215303311-e31f2e8b-5f47-4ff2-bea9-6c0233a84e61.png)

UPLOADED CompanyData.XLSX

![Image](https://user-images.githubusercontent.com/72959939/215303331-d14c6613-5e46-4948-a6c7-c33c5eafa3a2.png)


💯 **Backup of Files**

- Student
![Image](https://user-images.githubusercontent.com/72959939/215303490-51cd2de4-a28a-4fae-8abf-b96487c7b3c0.png)


- Company
![Image](https://user-images.githubusercontent.com/72959939/215303425-ce02fd43-076a-41e5-a872-a8eb88924341.png)

**Comment by Balqiskinanti** [comment]
If there are any missing headers in the XLSX file, it will still be stored in the backup directory but database will not be updates
