### ISSUE TITLE
Create backend assign students page

### ISSUE THREAD

**Issue by NPLeeWenKang** [devops-assignment1-team1/ias#34]
**Requirements**

- [x] GET all students
- [x] GET all students filtered by `status`
- [x] PATCH update student's status and company assignment
- [x] Get all company
- [x] Corresponding unit tests

**Comment by Balqiskinanti** [comment]
**1. GET students**
/api/v1/students


**2. PATCH students**
/api/v1/students
Body :
{"students":[{
  "student_id": "S10204973G",
  "status": "PENDING_CONFIRMATION" || "CONFIRMED" || "UNASSIGNED",
  "company_id": 3
}]}


**3. GET companies**
/api/v1/companies

**Comment by Balqiskinanti** [comment]
**unit tests**


![Image](https://user-images.githubusercontent.com/72959939/214108330-263c3c10-36e2-49e8-b2a5-1cd4c3c7e94a.png)

**Comment by chuadongen** [comment]
LGTM
