### ISSUE TITLE
Create frontend assign students page

### ISSUE THREAD

**Issue by Balqiskinanti** [devops-assignment1-team1/ias#36]
**Requirements**

- [x] Table with student name, preference, company list and status list
- [x] Updates the database whenever there is a change to the company / status
- [x] Corresponding test cases

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/215095857-71ffe1c1-d5a2-45ce-b19e-cd432d249853.png)

**Comment by chuadongen** [comment]
LGTM
