### ISSUE TITLE
Create Dev Database Push Pipeline

### ISSUE THREAD

**Issue by NPLeeWenKang** [devops-assignment1-team1/ias#4]
**Requirements**

- [x] Trigger on push /database and on push workflow .yml file
- [x] Check all tables to see whether they have been created properly

**Pull Requests**

1. https://github.com/devops-assignment1-team1/ias/pull/8

**Comment by NPLeeWenKang** [comment]
Due to the quirks of docker, if the init SQL statement is incorrect, the container will still succeed in creating itself but the initial tables and data will not be inserted. So to test the database, the database docker is brought up on every trigger and the database is queried to ensure that each table has been created successfully.

**Comment by chuadongen** [comment]
LGTM
