### ISSUE TITLE
Create backend prepare email page

### ISSUE THREAD

**Issue by Balqiskinanti** [devops-assignment1-team1/ias#40]
**Requirements**

- [x] Delete all files in the current email directories if any 
- [x] Generate emails files inside email directories created in settings page (with resume attachment)
- [x] Generate emails files inside email directories created in settings page (without resume attachment)
- [x] Create corresponding unit tests

**Comment by Balqiskinanti** [comment]
POST
/api/v1/students/generateEmail

**Comment by chuadongen** [comment]
LGTM
