### ISSUE TITLE
Create frontend prepare email page

### ISSUE THREAD

**Issue by Balqiskinanti** [devops-assignment1-team1/ias#43]
**requirements**

- [x] Display only students with "PENDING_CONFIRMATION" status
- [x] When click on "generate" button, create a toast button if it passes and a error toast when it fails.
- [x] Students with no resume will still return success but toast button will show which students are missing resumes.
- [x] Create the corresponding unit tests.

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/215095902-de527b23-7d2d-4f75-aa6e-7b5a6062143f.png)

**Comment by chuadongen** [comment]
LGTM
