### ISSUE TITLE
(QA) Create test cases for assign studens and preprare email page

### ISSUE THREAD

**Issue by lincolnchia** [devops-assignment1-team1/ias#48]
Requirements:

- [x] Check the link between matching of students with preparing an email.
- [x] Check if the email that is prepared contains the right student information.
- [x] Check that students with no resume will be flagged during preparing email.

Refer to assignment_testcase file on Microsoft Teams.

**Comment by chuadongen** [comment]
LGTM

**Comment by NPLeeWenKang** [comment]
LGTM
