### ISSUE TITLE
Create Prod PR Pipeline

### ISSUE THREAD

**Issue by NPLeeWenKang** [devops-assignment1-team1/ias#49]
**Requirements**

- [x] Trigger on PR to prod
- [x] Trigger unit test
- [x] Trigger sonarcloud scan
- [x] Trigger integration test (leave out first)
- [x] Trigger publishing of test results
- [x] Send notifications to appropriate stakeholder.

**Pull Requests**

1. https://github.com/devops-assignment1-team1/ias/pull/52

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/215090007-c99f3599-8f8d-4db4-b131-211e4d20f136.png)

Is an identical copy to the one in https://github.com/devops-assignment1-team1/ias/issues/18

**Comment by chuadongen** [comment]
LGTM, will test in release next sprint
