### ISSUE TITLE
Dockerize database

### ISSUE THREAD

**Issue by NPLeeWenKang** [devops-assignment1-team1/ias#5]
**Requirements**

- [x] Containerize the database using docker-compose.

**Pull Requests**

1. https://github.com/devops-assignment1-team1/ias/pull/7

**Comment by NPLeeWenKang** [comment]
Brings up a MySQL database and database admin console. The admin console can be accessed via `localhost:8080` and can be used as a CRUD interface for development.

**Comment by chuadongen** [comment]
LGTM
