### ISSUE TITLE
Create Prod Tag Push Pipeline

### ISSUE THREAD

**Issue by NPLeeWenKang** [devops-assignment1-team1/ias#50]
**Requirements**

- [x] Trigger on push tag
- [x] Perform unit tests
- [x] Perform integration test (leave out first)
- [x] trigger publishing of test results
- [x] Create zip file with source code, reports and testing files removed (reduce space)
- [x] Create release

**Pull Requests**

**Comment by NPLeeWenKang** [comment]
![Image](https://user-images.githubusercontent.com/73012553/215090233-06724802-b3e5-457d-819f-9a33ba24fbb1.png)

Very similar to https://github.com/devops-assignment1-team1/ias/issues/18 and https://github.com/devops-assignment1-team1/ias/issues/49, but sonarcloud analysis is not done. This is because sonarcloud analysis is not needed after the work has been deployed to prod. So this pipeline simply performs the final integration and unit test and creates a release.

**Comment by chuadongen** [comment]
LGTM
