### ISSUE TITLE
Perform manual test and create integration tests for Main, Upload Data and Settings page

### ISSUE THREAD

**Issue by verrgod** [devops-assignment1-team1/ias#55]
**Requirements**

- [x] Manual test for upload data
- [x] Manual test for settings
- [x] Integration test for upload data
- [x] Integration test for settings
- [x] Integration tests should match manual tests performed

**Comment by verrgod** [comment]
Manual test cases done, refer to **T-1** to **T-3** at
_https://docs.google.com/spreadsheets/d/15o9q1sYRDCx7XLghldSOlxmS3vM21BHYAjawwnBevcc/edit#gid=0_

**Comment by NPLeeWenKang** [comment]
LGTM
