### ISSUE TITLE
Perform manual test and create integration tests for Prepare Email and Assign Student page

### ISSUE THREAD

**Issue by verrgod** [devops-assignment1-team1/ias#56]
**Requirements**

- [x] Manual test for prepare email
- [x] Manual test for assign students
- [x] Integration test for prepare email
- [x] Integration test for assign students
- [x] Integration tests should match manual tests performed

**Comment by verrgod** [comment]
Manual test cases done, refer to **T-4** to **T-7** at
_https://docs.google.com/spreadsheets/d/15o9q1sYRDCx7XLghldSOlxmS3vM21BHYAjawwnBevcc/edit#gid=0_

**Comment by NPLeeWenKang** [comment]
LGTM
