### ISSUE TITLE
Change datepicker to string

### ISSUE THREAD

**Issue by chuadongen** [devops-assignment1-team1/ias#82]
- [x] Update datepicker to string
- [x] Corresponding Unit tests

**Comment by Balqiskinanti** [comment]
![Image](https://user-images.githubusercontent.com/72959939/218367202-c353c1c7-e67a-4381-9b71-a42eec125119.png)

**Comment by Balqiskinanti** [comment]
Unit tests


![Image](https://user-images.githubusercontent.com/72959939/218367306-aacdd517-52a3-42a2-b9d7-0f684fbad674.png)

**Comment by Balqiskinanti** [comment]
LGTM
