### ISSUE TITLE
Modify manual & integration tests to reflect datepicker to string change

### ISSUE THREAD

**Issue by verrgod** [devops-assignment1-team1/ias#84]
**Requirements**

- [x] Update manual test cases to reflect the change
- [x] Correspond integration test code

**Comment by verrgod** [comment]
Manual testing for T-1 reflect new datepicker to string change.

![Image](https://user-images.githubusercontent.com/74231870/218364046-4975c60f-ad42-4486-be3b-c9921e98a188.png)

Manual testing for T-3 reflect new datepicker to string change.

![Image](https://user-images.githubusercontent.com/74231870/218364085-52f9a24f-fb83-4caa-b133-ed9c8eb1daec.png)

**Comment by lincolnchia** [comment]
Integration test code reflect new changes

**Comment by Balqiskinanti** [comment]
LGTM
