### ISSUE TITLE
Create navbar & Footer

### ISSUE THREAD

**Issue by chuadongen** [devops-assignment1-team1/ias#9]
**Requirements**

- [x] Create navbar
- [x] Create footer
- [x] Add to app.js
- [x] Create corresponding unit tests (PPP)

**Comment by Balqiskinanti** [comment]
**Current page** 


![Image](https://user-images.githubusercontent.com/72959939/212671053-1b065a10-e4a3-45e2-8239-4437155baddd.png)


**Unit test results**


![Image](https://user-images.githubusercontent.com/72959939/212671099-219baf7a-bfdc-4404-8529-cb252c9d765e.png)

**Comment by Balqiskinanti** [comment]
Done with Dong En 🥳

**Comment by NPLeeWenKang** [comment]
LGTM
